- name: stop firewalld
  service:
    name: firewalld
    state: stopped
  ignore_errors: yes

- name: uninstall firewalld
  package:
    name: firewalld
    state: absent
  become: yes

- name: package installation
  package:
    name: "{{ item }}"
    state: installed
  with_items:
    - iptables
    - iptables-services

- name: set fact variables
  set_fact:
    ipv4_static: "{{ ipv4_static_rules }}"
