- name: install rabbitmq
  yum: name=https://dl.bintray.com/rabbitmq/rabbitmq-server-rpm/rabbitmq-server-3.6.14-1.el7.noarch.rpm state=installed 

- name: start service
  service: name=rabbitmq-server state=started eanbled=yes
