- name: install jdk
  yum:
    name: jre1.8
    state: latest
 
- name: hadoop Group create
  group:
    name: hadoop
    state: present

- name: hadoop User create
  user:
    name: hadoop
    state: present
    password: "{{ hadoop_password }}"
    group: hadoop

- name: update host file
  lineinfile:
    dest: /etc/hosts
    regexp: '{{ hostvars[item].ansible_default_ipv4.address }}.*{{ item }}$'
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}"
    state: present
  with_items: "{{ groups.all }}"
